/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.infox.telas;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.*;

/**
 *
 * @author gabri
 */
public class Telaprincipal extends javax.swing.JFrame {

    /**
     * Creates new form Telaprincipal
     */
    public Telaprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TF_Desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        TF_Usuario = new javax.swing.JLabel();
        TF_Data = new javax.swing.JLabel();
        TF_Menu = new javax.swing.JMenuBar();
        TF_MenCadastro = new javax.swing.JMenu();
        TF_MenCLi = new javax.swing.JMenuItem();
        TF_MenOS = new javax.swing.JMenuItem();
        TF_MenUsu = new javax.swing.JMenuItem();
        TF_Relatorio = new javax.swing.JMenu();
        TF_MenRelServ = new javax.swing.JMenuItem();
        TF_Ajuda = new javax.swing.JMenu();
        TF_Sobre = new javax.swing.JMenuItem();
        TF_Opcoes = new javax.swing.JMenu();
        TF_Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SistemaControle");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        TF_Desktop.setPreferredSize(new java.awt.Dimension(640, 480));

        javax.swing.GroupLayout TF_DesktopLayout = new javax.swing.GroupLayout(TF_Desktop);
        TF_Desktop.setLayout(TF_DesktopLayout);
        TF_DesktopLayout.setHorizontalGroup(
            TF_DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        TF_DesktopLayout.setVerticalGroup(
            TF_DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/logo.png"))); // NOI18N

        TF_Usuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TF_Usuario.setText("Usuário");

        TF_Data.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TF_Data.setText("Data");

        TF_MenCadastro.setText("Cadastro");

        TF_MenCLi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        TF_MenCLi.setText("Cliente");
        TF_MenCLi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_MenCLiActionPerformed(evt);
            }
        });
        TF_MenCadastro.add(TF_MenCLi);

        TF_MenOS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        TF_MenOS.setText("OS");
        TF_MenCadastro.add(TF_MenOS);

        TF_MenUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        TF_MenUsu.setText("Usuários");
        TF_MenUsu.setEnabled(false);
        TF_MenUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_MenUsuActionPerformed(evt);
            }
        });
        TF_MenCadastro.add(TF_MenUsu);

        TF_Menu.add(TF_MenCadastro);

        TF_Relatorio.setText("Relatório");
        TF_Relatorio.setEnabled(false);

        TF_MenRelServ.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        TF_MenRelServ.setText("Serviços");
        TF_MenRelServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_MenRelServActionPerformed(evt);
            }
        });
        TF_Relatorio.add(TF_MenRelServ);

        TF_Menu.add(TF_Relatorio);

        TF_Ajuda.setText("Ajuda");

        TF_Sobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        TF_Sobre.setText("Sobre");
        TF_Sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_SobreActionPerformed(evt);
            }
        });
        TF_Ajuda.add(TF_Sobre);

        TF_Menu.add(TF_Ajuda);

        TF_Opcoes.setText("Opções");

        TF_Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        TF_Sair.setText("Sair");
        TF_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_SairActionPerformed(evt);
            }
        });
        TF_Opcoes.add(TF_Sair);

        TF_Menu.add(TF_Opcoes);

        setJMenuBar(TF_Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TF_Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_Data)
                            .addComponent(TF_Usuario)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(TF_Usuario)
                .addGap(28, 28, 28)
                .addComponent(TF_Data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(35, 35, 35))
            .addComponent(TF_Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(853, 681));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TF_MenRelServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_MenRelServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_MenRelServActionPerformed

    private void TF_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_SairActionPerformed

        int sair = JOptionPane.showConfirmDialog(null," Você deseja sair ? " + JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_TF_SairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        TF_Data.setText(formatador.format(data));

    }//GEN-LAST:event_formWindowActivated

    private void TF_SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_SobreActionPerformed
       
    }//GEN-LAST:event_TF_SobreActionPerformed

    private void TF_MenUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_MenUsuActionPerformed
        // abrir formulario 
        TelaUsuario usuario = new  TelaUsuario();
        usuario.setVisible(true);
        TF_Desktop.add(usuario);
    }//GEN-LAST:event_TF_MenUsuActionPerformed

    private void TF_MenCLiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_MenCLiActionPerformed
        //chamando a tela cliente
        
    }//GEN-LAST:event_TF_MenCLiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu TF_Ajuda;
    private javax.swing.JLabel TF_Data;
    private javax.swing.JDesktopPane TF_Desktop;
    private javax.swing.JMenuItem TF_MenCLi;
    private javax.swing.JMenu TF_MenCadastro;
    private javax.swing.JMenuItem TF_MenOS;
    private javax.swing.JMenuItem TF_MenRelServ;
    public static javax.swing.JMenuItem TF_MenUsu;
    private javax.swing.JMenuBar TF_Menu;
    private javax.swing.JMenu TF_Opcoes;
    public static javax.swing.JMenu TF_Relatorio;
    private javax.swing.JMenuItem TF_Sair;
    private javax.swing.JMenuItem TF_Sobre;
    public static javax.swing.JLabel TF_Usuario;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
